### ISSUE TITLE
Issue with Templates

### ISSUE THREAD

**Issue by jonniebigodes** [storybookjs/repro-templates#1]
While working on the updates for the documentation on how to create a reproducible case in Storybook's issue tracker I stumbled across an issue with the templates listed. I checked only the stable release ones and got the following error on Stackblitz, preventing me and possibly any other user that tries to spin up a Storybook reproduction for his/her issue:

- Angular
```shell
info => Using implicit CSS loaders
info => Loading angular-cli config
info => Using angular project "angular:build" for configuring Storybook
info => Using angular-cli webpack config
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
7% setup compile fork-ts-checker-webpack-pluginStarting type checking service...
23% building 4/16 entries 864/1001 dependencies 67/351 modules[BABEL] Note: The code generator has deoptimised the styling of /home/projects/gqaimbjwz.github/node_modules/prettier/standalone.js as it exceeds the max of 500KB.
99% done plugins webpack-hot-middlewarewebpack built preview 5679c14aa22cb2ff7e80 in 90783ms
ModuleParseError: Module parse failed: Unexpected token (27:35)
File was processed with these loaders:
 * ./node_modules/style-loader/dist/cjs.js
 * ./node_modules/css-loader/dist/cjs.js
 * ./node_modules/postcss-loader/dist/cjs.js
 * ./node_modules/resolve-url-loader/index.js
 * ./node_modules/sass-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| if (module.hot) {
|   if (!content.locals || module.hot.invalidate) {
>     var isEqualLocals = Function() { [native code] };
|     var isNamedExport = !content.locals;
|     var oldLocals = isNamedExport ? namedExport : content.locals;
    at handleParseError (/home/projects/gqaimbjwz.github/node_modules/webpack/lib/NormalModule.js:933:19)
    at eval (/home/projects/gqaimbjwz.github/node_modules/webpack/lib/NormalModule.js:1037:5)
    at processResult (/home/projects/gqaimbjwz.github/node_modules/webpack/lib/NormalModule.js:755:11)
    at eval (/home/projects/gqaimbjwz.github/node_modules/webpack/lib/NormalModule.js:819:5)
    at eval (/home/projects/gqaimbjwz.github/node_modules/loader-runner/lib/LoaderRunner.js:406:3)
    at iterateNormalLoaders (/home/projects/gqaimbjwz.github/node_modules/loader-runner/lib/LoaderRunner.js:232:10)
    at eval (/home/projects/gqaimbjwz.github/node_modules/loader-runner/lib/LoaderRunner.js:205:6)
    at runSyncOrAsync (/home/projects/gqaimbjwz.github/node_modules/loader-runner/lib/LoaderRunner.js:143:11)
    at eval (/home/projects/gqaimbjwz.github/node_modules/loader-runner/lib/LoaderRunner.js:191:3)
    at handleResult (/home/projects/gqaimbjwz.github/node_modules/loader-runner/lib/loadLoader.js:53:2)
    at loadLoader (/home/projects/gqaimbjwz.github/node_modules/loader-runner/lib/loadLoader.js:35:10)
    at iteratePitchingLoaders (/home/projects/gqaimbjwz.github/node_modules/loader-runner/lib/LoaderRunner.js:182:2)
    at runLoaders (/home/projects/gqaimbjwz.github/node_modules/loader-runner/lib/LoaderRunner.js:397:2)
    at NormalModule.doBuild (/home/projects/gqaimbjwz.github/node_modules/webpack/lib/NormalModule.js:773:3)
    at NormalModule.build (/home/projects/gqaimbjwz.github/node_modules/webpack/lib/NormalModule.js:920:15)
    at eval (/home/projects/gqaimbjwz.github/node_modules/webpack/lib/Compilation.js:1322:12)
```
- CRA and CRA + TS
```shell
ERROR in ./.storybook/storybook-init-framework-entry.js
Module build failed (from ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js):
Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/read-wasm.js:8:13)
    at wasm (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/wasm.js:25:16)
    at eval (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/source-map-consumer.js:264:14)
    at async Object._loader (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js:81:9)
 @ multi ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-other-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/preview.js-generated-other-entry.js ./node_modules/storybook-addon-outline/dist/esm/preset/addDecorator.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry.js main[3]

ERROR in ./.storybook/preview.js-generated-config-entry.js
Module build failed (from ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js):
Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/read-wasm.js:8:13)
    at wasm (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/wasm.js:25:16)
    at eval (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/source-map-consumer.js:264:14)
    at async Object._loader (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js:81:9)
 @ multi ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-other-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/preview.js-generated-other-entry.js ./node_modules/storybook-addon-outline/dist/esm/preset/addDecorator.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry.js main[13]

ERROR in ./.storybook/generated-stories-entry.js
Module build failed (from ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js):
Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/read-wasm.js:8:13)
    at wasm (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/wasm.js:25:16)
    at eval (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/source-map-consumer.js:264:14)
    at async Object._loader (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js:81:9)
 @ multi ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-other-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/preview.js-generated-other-entry.js ./node_modules/storybook-addon-outline/dist/esm/preset/addDecorator.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry.js main[14]
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.22 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core-common/dist/cjs/templates/index.ejs] 1.97 KiB {HtmlWebpackPlugin_0} [built]
ModuleBuildError: Module build failed (from ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js):
Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/read-wasm.js:8:13)
    at wasm (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/wasm.js:25:16)
    at eval (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/source-map-consumer.js:264:14)
    at async Object._loader (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js:81:9)
    at eval (/home/projects/jvmikwnzb.github/node_modules/webpack/lib/NormalModule.js:316:20)
    at eval (/home/projects/jvmikwnzb.github/node_modules/loader-runner/lib/LoaderRunner.js:367:11)
    at eval (/home/projects/jvmikwnzb.github/node_modules/loader-runner/lib/LoaderRunner.js:233:18)
    at context.callback (/home/projects/jvmikwnzb.github/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at eval (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js:99:7)
ModuleBuildError: Module build failed (from ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js):
Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/read-wasm.js:8:13)
    at wasm (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/wasm.js:25:16)
    at eval (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/source-map-consumer.js:264:14)
    at async Object._loader (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js:81:9)
    at eval (/home/projects/jvmikwnzb.github/node_modules/webpack/lib/NormalModule.js:316:20)
    at eval (/home/projects/jvmikwnzb.github/node_modules/loader-runner/lib/LoaderRunner.js:367:11)
    at eval (/home/projects/jvmikwnzb.github/node_modules/loader-runner/lib/LoaderRunner.js:233:18)
    at context.callback (/home/projects/jvmikwnzb.github/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at eval (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js:99:7)
ModuleBuildError: Module build failed (from ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js):
Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/read-wasm.js:8:13)
    at wasm (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/wasm.js:25:16)
    at eval (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/source-map/lib/source-map-consumer.js:264:14)
    at async Object._loader (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js:81:9)
    at eval (/home/projects/jvmikwnzb.github/node_modules/webpack/lib/NormalModule.js:316:20)
    at eval (/home/projects/jvmikwnzb.github/node_modules/loader-runner/lib/LoaderRunner.js:367:11)
    at eval (/home/projects/jvmikwnzb.github/node_modules/loader-runner/lib/LoaderRunner.js:233:18)
    at context.callback (/home/projects/jvmikwnzb.github/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at eval (/home/projects/jvmikwnzb.github/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js:99:7)
```

- React without CRA / WebComponents Lit 2 / HTML / Preact / Svelte / Vue 2 / Vue 3
```shell
ERROR in ./stories/page.css 20:35
Module parse failed: Unexpected token (20:35)
File was processed with these loaders:
 * ./node_modules/style-loader/dist/cjs.js
 * ./node_modules/css-loader/dist/cjs.js
 * ./node_modules/postcss-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| if (module.hot) {
|   if (!content.locals || module.hot.invalidate) {
>     var isEqualLocals = Function() { [native code] };
|     var oldLocals = content.locals;
| 
 @ ./stories/Page.jsx 4:0-20
 @ ./stories/Page.stories.jsx
 @ ./stories sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|ts|tsx))$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-other-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/preview.js-generated-other-entry.js ./node_modules/storybook-addon-outline/dist/esm/preset/addDecorator.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined

ERROR in ./stories/header.css 20:35
Module parse failed: Unexpected token (20:35)
File was processed with these loaders:
 * ./node_modules/style-loader/dist/cjs.js
 * ./node_modules/css-loader/dist/cjs.js
 * ./node_modules/postcss-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| if (module.hot) {
|   if (!content.locals || module.hot.invalidate) {
>     var isEqualLocals = Function() { [native code] };
|     var oldLocals = content.locals;
| 
 @ ./stories/Header.jsx 4:0-22
 @ ./stories/Page.jsx
 @ ./stories/Page.stories.jsx
 @ ./stories sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|ts|tsx))$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-other-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/preview.js-generated-other-entry.js ./node_modules/storybook-addon-outline/dist/esm/preset/addDecorator.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined

ERROR in ./stories/button.css 20:35
Module parse failed: Unexpected token (20:35)
File was processed with these loaders:
 * ./node_modules/style-loader/dist/cjs.js
 * ./node_modules/css-loader/dist/cjs.js
 * ./node_modules/postcss-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| if (module.hot) {
|   if (!content.locals || module.hot.invalidate) {
>     var isEqualLocals = Function() { [native code] };
|     var oldLocals = content.locals;
| 
 @ ./stories/Button.jsx 14:0-22
 @ ./stories/Header.jsx
 @ ./stories/Page.jsx
 @ ./stories/Page.stories.jsx
 @ ./stories sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|ts|tsx))$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-other-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/preview.js-generated-other-entry.js ./node_modules/storybook-addon-outline/dist/esm/preset/addDecorator.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.22 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core-common/dist/cjs/templates/index.ejs] 1.97 KiB {HtmlWebpackPlugin_0} [built]
ModuleParseError: Module parse failed: Unexpected token (20:35)
File was processed with these loaders:
 * ./node_modules/style-loader/dist/cjs.js
 * ./node_modules/css-loader/dist/cjs.js
 * ./node_modules/postcss-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| if (module.hot) {
|   if (!content.locals || module.hot.invalidate) {
>     var isEqualLocals = Function() { [native code] };
|     var oldLocals = content.locals;
| 
    at handleParseError (/home/projects/mklilovqz.github/node_modules/webpack/lib/NormalModule.js:469:19)
    at eval (/home/projects/mklilovqz.github/node_modules/webpack/lib/NormalModule.js:503:5)
    at eval (/home/projects/mklilovqz.github/node_modules/webpack/lib/NormalModule.js:358:12)
    at eval (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/LoaderRunner.js:373:3)
    at iterateNormalLoaders (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at eval (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/LoaderRunner.js:186:6)
    at runSyncOrAsync (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at eval (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/LoaderRunner.js:178:3)
    at loadLoader (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/loadLoader.js:47:3)
    at iteratePitchingLoaders (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
    at NormalModule.doBuild (/home/projects/mklilovqz.github/node_modules/webpack/lib/NormalModule.js:295:3)
    at NormalModule.build (/home/projects/mklilovqz.github/node_modules/webpack/lib/NormalModule.js:446:15)
    at Compilation.buildModule (/home/projects/mklilovqz.github/node_modules/webpack/lib/Compilation.js:739:10)
    at eval (/home/projects/mklilovqz.github/node_modules/webpack/lib/Compilation.js:981:14)
    at eval (/home/projects/mklilovqz.github/node_modules/webpack/lib/NormalModuleFactory.js:409:6)
ModuleParseError: Module parse failed: Unexpected token (20:35)
File was processed with these loaders:
 * ./node_modules/style-loader/dist/cjs.js
 * ./node_modules/css-loader/dist/cjs.js
 * ./node_modules/postcss-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| if (module.hot) {
|   if (!content.locals || module.hot.invalidate) {
>     var isEqualLocals = Function() { [native code] };
|     var oldLocals = content.locals;
| 
    at handleParseError (/home/projects/mklilovqz.github/node_modules/webpack/lib/NormalModule.js:469:19)
    at eval (/home/projects/mklilovqz.github/node_modules/webpack/lib/NormalModule.js:503:5)
    at eval (/home/projects/mklilovqz.github/node_modules/webpack/lib/NormalModule.js:358:12)
    at eval (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/LoaderRunner.js:373:3)
    at iterateNormalLoaders (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at eval (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/LoaderRunner.js:186:6)
    at runSyncOrAsync (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at eval (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/LoaderRunner.js:178:3)
    at loadLoader (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/loadLoader.js:47:3)
    at iteratePitchingLoaders (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
    at NormalModule.doBuild (/home/projects/mklilovqz.github/node_modules/webpack/lib/NormalModule.js:295:3)
    at NormalModule.build (/home/projects/mklilovqz.github/node_modules/webpack/lib/NormalModule.js:446:15)
    at Compilation.buildModule (/home/projects/mklilovqz.github/node_modules/webpack/lib/Compilation.js:739:10)
    at eval (/home/projects/mklilovqz.github/node_modules/webpack/lib/Compilation.js:981:14)
    at eval (/home/projects/mklilovqz.github/node_modules/webpack/lib/NormalModuleFactory.js:409:6)
ModuleParseError: Module parse failed: Unexpected token (20:35)
File was processed with these loaders:
 * ./node_modules/style-loader/dist/cjs.js
 * ./node_modules/css-loader/dist/cjs.js
 * ./node_modules/postcss-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| if (module.hot) {
|   if (!content.locals || module.hot.invalidate) {
>     var isEqualLocals = Function() { [native code] };
|     var oldLocals = content.locals;
| 
    at handleParseError (/home/projects/mklilovqz.github/node_modules/webpack/lib/NormalModule.js:469:19)
    at eval (/home/projects/mklilovqz.github/node_modules/webpack/lib/NormalModule.js:503:5)
    at eval (/home/projects/mklilovqz.github/node_modules/webpack/lib/NormalModule.js:358:12)
    at eval (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/LoaderRunner.js:373:3)
    at iterateNormalLoaders (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at eval (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/LoaderRunner.js:186:6)
    at runSyncOrAsync (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at eval (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/LoaderRunner.js:178:3)
    at loadLoader (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/loadLoader.js:47:3)
    at iteratePitchingLoaders (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/home/projects/mklilovqz.github/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
    at NormalModule.doBuild (/home/projects/mklilovqz.github/node_modules/webpack/lib/NormalModule.js:295:3)
    at NormalModule.build (/home/projects/mklilovqz.github/node_modules/webpack/lib/NormalModule.js:446:15)
    at Compilation.buildModule (/home/projects/mklilovqz.github/node_modules/webpack/lib/Compilation.js:739:10)
    at eval (/home/projects/mklilovqz.github/node_modules/webpack/lib/Compilation.js:981:14)
    at eval (/home/projects/mklilovqz.github/node_modules/webpack/lib/NormalModuleFactory.js:409:6
```

The change to this is the component's name.

@shilman any ideas? 

What strikes me the strangest is that this was working yesterday (Tuesday) when I shared a reproduction with you. 

To reproduce this:
- Click any of the latest stable release templates
- Wait for StackBlitz to run through the bootup process and dependencies install and run the startup process with `start-storybook`.

I'll wait for your feedback on this in order to update the docs.

**Comment by shilman** [comment]
Thanks @jonniebigodes. One possibility is that it's a regression on our side, possibly caused by the big Babel change in 6.4 (tho unlikely since that's feature flagged). Another possibility is that it's a problem with Stackblitz.

A few questions:
- is this for both `next` AND `latest`?
- do these same projects work if you clone locally to your dev machine and run?

**Comment by jonniebigodes** [comment]
I've only tested with the latest stable release. I'll check the `next` branch and run them locally and let you know.

**Comment by jonniebigodes** [comment]
I've just completed the run with the `next` branch on Stackblitz:

- Angular
Breaks with the same error as above

- React without CRA
Breaks with the same error as above

- CRA 
Breaks with the same error as above

- CRA with TypeScript
Spinning up React TS template yields the following error:

![react-ts-repro](https://user-images.githubusercontent.com/22988955/131757020-c48ef002-7fc4-4b19-b02d-959c9c3d1065.png)


- React without CRA / WebComponents Lit 2 / HTML / Preact / Svelte / Vue 2 / Vue 3
Breaks with the same error as above


Locally on my machine, both `main` and `next` branches show green across the board. They are working as expected. It seems that is something on their side, as not only main and next branches throw errors.
